version: '3'
services:
    db:
        # restart: always
        image: postgres:13-alpine
        ports:
            # Map postgresql port for easy PyCharm integration.
            # Make sure no postgres process on the host is already using the port.
            - 5432:5432
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
    rabbit:
        # restart: always
        image: rabbitmq:3.9-alpine
    qxsms:
        # restart: always
        image: qxsms:local
        user: "CHANGE_ME:CHANGE_ME" # TODO: Change this to your user and group id
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - QXSMS_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER
            - POSTGRES_DB
            - QXSMS_DEBUG=true
            - PYTHONUNBUFFERED=1
        env_file:
            - .env
        ports:
            - 8000:8000
        entrypoint:
            - ./entrypoint.dev.sh
        volumes:
            - .:/qxsms
        depends_on:
            - db
            - rabbit
    worker:
        # restart: always
        image: qxsms:local
        user: "CHANGE_ME:CHANGE_ME" # TODO: Change this to your user and group id
        environment:
            - QXSMS_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER
            - POSTGRES_DB
            - QXSMS_DEBUG=true
        env_file:
            - .env
        command: sh -c "python manage.py compilemessages; wait-for-it -t 60 --service rabbit:5672 -- celery -A qxsms worker -l INFO --uid=nobody --gid=nogroup"
        volumes:
            - .:/qxsms
        depends_on:
            - db
            - rabbit
    docs:
        image: squidfunk/mkdocs-material:9
        ports:
            - 8888:8000
        volumes:
            - ./docs/user:/docs
volumes:
    dbdata:
