# Generated by Django 2.2.25 on 2022-01-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panelist', '0003_auto_20211007_1427'),
        ('distributions', '0003_auto_20210927_1025'),
        ('hq', '0002_panel_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsstatus', models.CharField(max_length=255, null=True)),
                ('bouncereason', models.CharField(max_length=255, null=True)),
                ('datefile', models.DateTimeField(null=True)),
                ('msgdist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.MessageDistribution')),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelist.Profile')),
            ],
        ),
    ]
