# Generated by Django 2.2.24 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('qx_contact_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('qx_id', models.CharField(max_length=20, null=True, unique=True)),
                ('qx_import_id', models.CharField(max_length=20, null=True, unique=True)),
                ('qx_created_date', models.DateTimeField(null=True)),
                ('qx_list_id', models.CharField(max_length=20, null=True, unique=True)),
                ('expiration_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('qx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('invite', 'Email'), ('emailSubject', 'Email subject'), ('smsInvite', 'SMS')], max_length=20)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('qx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('qx_id', models.CharField(max_length=20, null=True, unique=True)),
                ('qx_import_id', models.CharField(max_length=20, null=True, unique=True)),
                ('qx_created_date', models.DateTimeField(null=True)),
                ('qx_batch_id', models.CharField(max_length=20, null=True, unique=True)),
                ('contact_mode', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'SMS')])),
                ('target', models.PositiveSmallIntegerField(choices=[(0, 'All'), (1, 'Not finished (proper target for reminders)'), (2, 'Finished')], verbose_name='Target recipients')),
                ('send_date', models.DateTimeField(null=True)),
                ('fallback_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallback', to='distributions.MessageDistribution')),
                ('link_distribution', models.ForeignKey(limit_choices_to={'qx_id__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='messagedistributions', related_query_name='messagedistribution', to='distributions.LinkDistribution')),
                ('links', models.ManyToManyField(related_name='message_distributions', related_query_name='message_distribution', to='distributions.Link')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_message_of_set', related_query_name='email_message_of', to='distributions.Message')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_subject_of_set', related_query_name='email_subject_of', to='distributions.Message')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
