# Generated by Django 2.2.24 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hq', '0001_initial'),
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdistribution',
            name='panels',
            field=models.ManyToManyField(related_name='distributions', to='hq.Panel'),
        ),
        migrations.AddField(
            model_name='linkdistribution',
            name='survey',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distributions.Survey'),
        ),
        migrations.AddField(
            model_name='link',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='distributions.LinkDistribution'),
        ),
    ]
