# Generated by Django 2.2.24 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panelist', '0001_initial'),
        ('distributions', '0002_auto_20210927_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='panelist.Profile', to_field='uid'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('profile', 'distribution')},
        ),
    ]
