# Generated by Django 2.2.25 on 2022-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qxauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='last name'),
        ),
    ]
