# Generated by Django 2.2.24 on 2021-09-27 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panelist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blankslotvalue',
            name='blankslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelist.BlankSlot'),
        ),
        migrations.AddField(
            model_name='blankslotvalue',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelist.Profile'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('panel', 'ess_id'), name='unique_panelist'),
        ),
        migrations.AlterUniqueTogether(
            name='blankslotvalue',
            unique_together={('profile', 'blankslot')},
        ),
    ]
