# Generated by Django 2.2.25 on 2022-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelist', '0003_auto_20211007_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='delete_data',
            new_name='delete_contact_data',
        ),
        migrations.AddField(
            model_name='profile',
            name='anonymized_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delete_survey_data',
            field=models.BooleanField(default=False),
        ),
    ]
