# Generated by Django 2.2.24 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTaskImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_group_id', models.CharField(max_length=100)),
                ('celery_2ndgroup_id', models.CharField(max_length=100, null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('dry_run', models.BooleanField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hq.Panel')),
            ],
        ),
    ]
