# Generated by Django 3.2.12 on 2022-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_grouptaskimport_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptaskimport',
            name='celery_2ndgroup_id',
        ),
        migrations.RemoveField(
            model_name='grouptaskimport',
            name='uploader',
        ),
    ]
