# Generated by Django 3.2.12 on 2022-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20220406_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptaskimport',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
